[project]
name = "repl-nix-wireguardmonitor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0.3",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "streamlit>=1.39.0",
]
